### ISSUE TITLE
AttributeError: type object 'Yelp' has no attribute 'urls

### ISSUE THREAD

**Issue by pranonrahman** [bidishasamantakgp/CTVAE#1]
I am trying to fine-tune your model on my custom dataset. The dataset is formatted the same way as the Yelp dataset. When I am trying to run train_datasets.py, it gives me the following error
```
AttributeError: type object 'Yelp' has no attribute 'urls'
```

**Comment by bidishasamantakgp** [comment]
Hi,

You need to follow the steps to place the dataset folders in the correct path. Otherwise the code will try to download the data from a given url. In our case we didn't add any url in the dataset_yelp.py as we preprocess and store it in the required path.
