### ISSUE TITLE
Question in RealNVP.

### ISSUE THREAD

**Issue by shangqwe123** [bidishasamantakgp/CTVAE#2]
It is a great work, but I have a question. 
As described in paper, z is split into z[:-1] and z[-1:] in RealNVP . However, z is split into z[:dim//2] and z[dim//2:] in your code. 
Is it a mistake or something I misunderstand?

Thanks.

**Comment by bidishasamantakgp** [comment]
The split of the RealNVP is kept as d/2 here because that is a more generic implementation
In this case you can supervise d/2 properties simultaneously on that d/2 dimensions.

However, the experiments reported in the paper are done using z[:-1] and z[-1:].
